update readme files
AdguardTeam/LegalDocs pull request #105
Opened 2024-09-06 13:02 UTC by SeverAnna

2024-09-06 13:56 UTC, el-termikael approved these changes

2024-09-10 09:59 UTC, ameshkov requested changes

2024-09-10 09:59 UTC, ameshkov commented on adguard-dns.io/README.md
> +EULA
![image](https://github.com/user-attachments/assets/1d2db1c2-a76c-496c-87d7-e62ef6057e2e)

2024-09-10 09:59 UTC, ameshkov commented on adguard-dns.io/README.md
> +Privacy policy
Make each of them a link to the document you're referring to.

2024-09-16 20:35 UTC, ameshkov approved these changes

2024-09-16 20:35 UTC, merged