add ToC of AdGuard Aff Program
AdguardTeam/LegalDocs pull request #118
Opened 2024-11-26 13:18 UTC by el-termikael

2024-11-27 09:11 UTC, ameshkov requested changes
There are a lot of places where you need either to use list formatting or separate paragraphs because markdown will disregard new lines.

2024-11-27 09:11 UTC, ameshkov commented on adguardpartner.com/terms-and-conditions.html.md
> +AdGuard does not request or have access to your accounts in third-party payment services.
```suggestion

AdGuard does not request or have access to your accounts in third-party payment services.
```

2024-11-27 09:12 UTC, ameshkov requested changes

2024-11-27 09:12 UTC, ameshkov commented on adguardpartner.com/terms-and-conditions.html.md
> +Website: https://aff.adguard.com/
adguardpartner
```suggestion
Website: https://adguardpartner.com/
```

2024-11-27 09:15 UTC, bniwredyc commented on adguardpartner.com/terms-and-conditions.html.md
> +AdGuard is the rights holder of AdGuard Ad Blocker: https://adguard.com/, AdGuard VPN: https://adguard-vpn.com/, and AdGuard DNS: https://adguard-dns.io/ (hereafter, collectively, the “Software”). We
Let's make all links pretty like ```[adguard.com](https://adguard.com/)```

2024-11-27 09:15 UTC, bniwredyc commented on adguardpartner.com/terms-and-conditions.html.md
> +Email: support@adguard.com
In this case ```[support@adguard.com](mailto:support@adguard.com)```

2024-11-28 11:39 UTC, ameshkov requested changes

2024-11-28 11:39 UTC, ameshkov commented on adguardpartner.com/terms-and-conditions.html.md
> +AdGuard is the rights holder of AdGuard Ad Blocker: [adguard.com](https://adguard.com/), AdGuard VPN: [adguard-vpn.com](https://adguard-vpn.com/), and AdGuard DNS: [adguard-dns.io](https://adguard-dn
```suggestion
AdGuard is the rights holder of AdGuard Ad Blocker: [adguard.com](https://adguard.com/), AdGuard VPN: [adguard-vpn.com](https://adguard-vpn.com/), and AdGuard DNS: [adguard-dns.io](https://adguard-dns.io/) (hereafter, collectively, the “Software”). We also operate the websites of the Software mentioned above (hereafter, the “Software Websites”), as well as the AdGuard Affiliate Account service (hereafter, the “Affiliate Account”) available at [adguardpartner.com](https://adguardpartner.com/) (hereafter, the “Affiliate Website”).
```

2024-11-28 11:43 UTC, ameshkov requested changes

2024-11-28 11:43 UTC, ameshkov commented on adguardpartner.com/terms-and-conditions.html.md
> +- (a) You earn your commission for a subscription purchase when
Fix formatting here
![image](https://github.com/user-attachments/assets/3f6d3e15-dea8-4be1-93c2-8f068b09acd9)

2024-11-28 11:43 UTC, ameshkov commented on adguardpartner.com/terms-and-conditions.html.md
> +(a) TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER ADGUARD NOR ITS SUPPLIERS OR AFFILIATES SHALL BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE, COVER OR CONSEQU
Use list formatting here

2024-11-28 14:58 UTC, ameshkov approved these changes

2024-11-28 15:45 UTC, merged