translated AdGuard VPN Privacy policy to Russian
AdguardTeam/LegalDocs pull request #73
Opened 2022-09-08 18:43 UTC by el-termikael

2022-09-09 16:52 UTC, vbagirov requested changes

2022-09-09 16:52 UTC, vbagirov commented on dns_privacy_policy/en/privacy-main.md
> +Whenever an AdGuard DNS server (except non-filtering servers) receives a request to a domain that’s considered to be an ad or tracking domain, it returns an “unspecified IP” response (0.0.0.0). Whene
`0.0.0.0` в кавычки наверное

2022-09-09 16:52 UTC, vbagirov commented on dns_privacy_policy/en/privacy-main.md
> +* We store aggregated performance metrics of our DNS server, namely the number of complete requests to a particular server, the number of blocked requests, and the speed of processing requests.
ранее говорили про "серверы", а тут в ед. числе про "сервер", надо наверное определиться

2022-09-09 16:52 UTC, vbagirov commented on dns_privacy_policy/en/privacy-main.md
> +We believe that privacy is a fundamental human right. That's why we are transparent about what AdGuard does, and explain the purpose of every little bit of information that may be gathered by our app
может где то тут в начале про опенсорс указать?

2022-09-09 16:52 UTC, vbagirov commented on dns_privacy_policy/en/privacy-main.md
> +* We also log how many times this or that tracker has been blocked. We need this information to remove outdated rules from our filters.
только трекер? с рекламными доменами нет?

2022-09-09 16:52 UTC, vbagirov commented on dns_privacy_policy/en/privacy-main.md
> +### When You Are Using Our Website
а раздел "когда вы используете паблик днс" не нужен потому что ничего не собираем?

2022-09-09 16:52 UTC, vbagirov commented on dns_privacy_policy/en/privacy-main.md
> +* Billing and payment information. If you buy a subscription to AdGuard DNS, we will need to know your contact details. We conduct all transactions via [the Paddle payment provider](https://paddle.co
subscription to Private AdGuard DNS?

2022-09-09 16:52 UTC, vbagirov commented on dns_privacy_policy/en/privacy-main.md
> +AdGuard DNS users may opt to use the “private AdGuard DNS” server. This functionality allows them to control what is done to their DNS queries, observe statistics and query logs.
"what is done to" выглядит странно, можно просто вырезать мне кажется

2022-09-09 16:52 UTC, vbagirov commented on dns_privacy_policy/en/privacy-main.md
> +We retain Personal Data for as long as necessary to continue providing you with our products and services, or until you revoke your consent to share this information.
we RETAIN .... until you revoke consent to SHARE

нет противоречия?

2022-09-09 16:52 UTC, vbagirov commented on dns_privacy_policy/en/privacy-main.md
> +* Request information about what data about you we store and for how long, and if we did not collect it directly from you, you can request information about its source;
уточнить, как можно запросить её?

2022-09-09 16:52 UTC, vbagirov commented on dns_privacy_policy/en/privacy-main.md
> +* Request information about what data about you we store and for how long, and if we did not collect it directly from you, you can request information about its source;
по следующему пункту аналогично

2022-09-12 09:57 UTC, vbagirov requested changes

2022-09-12 09:57 UTC, vbagirov commented on vpn_privacy_policy/ru/privacy-main.md
> +Данные, которые мы собираем, включают информацию, необходимую для полной функциональности сервисов и сайта AdGuard VPN. Мы не собираем ничего с целью отслеживания и делаем все для защиты полученной и
функциональности -- наверное "для полноценного функционирования" лучше звучит?

2022-09-12 09:57 UTC, vbagirov commented on vpn_privacy_policy/ru/privacy-main.md
> +ADGUARD SOFTWARE LIMITED (далее «мы») собирает и обрабатывает ваши личные данные в соответствии с этой Политикой конфиденциальности и в согласии с применимыми законами о защите данных. В данной Полит
Не знаю, как лучше -- может "Мы" с большой писать везде? Хотя я вижу что в полиси блокера например здесь с большой, а по тексту с маленькой

2022-09-12 09:57 UTC, vbagirov commented on vpn_privacy_policy/ru/privacy-main.md
> +ADGUARD SOFTWARE LIMITED (далее «мы») собирает и обрабатывает ваши личные данные в соответствии с этой Политикой конфиденциальности и в согласии с применимыми законами о защите данных. В данной Полит
и если с большой, то что делать со всякими "Нас", "Наш" и т.д.

2022-09-12 09:57 UTC, vbagirov commented on vpn_privacy_policy/ru/privacy-main.md
> +* Диагностическая информация/информация об устройстве. По умолчанию мы ничего не собираем. Но если вы дадите согласие, то мы будем собирать анонимную диагностическую информацию (для отчетов об ошибка
отчётов - и вообще везде ё проверить

2022-09-12 09:57 UTC, vbagirov commented on vpn_privacy_policy/ru/privacy-main.md
> +* Диагностическая информация/информация об устройстве. По умолчанию мы ничего не собираем. Но если вы дадите согласие, то мы будем собирать анонимную диагностическую информацию (для отчетов об ошибка
"в отдельных уведомлениях о конфиденциальности" - а они есть у впна?

2022-09-12 09:57 UTC, vbagirov commented on vpn_privacy_policy/ru/privacy-main.md
> +Мы следуем Общему регламенту по защите данных ЕС ("GDPR"), который определяет личные данные как: «...любую информацию, относящуюся к идентифицированному или идентифицируемому физическому лицу («субъе
цитату лучше оформить как в днс полиси, отдельным блокквоутом

2022-09-12 09:57 UTC, vbagirov commented on vpn_privacy_policy/ru/privacy-main.md
> +* Система контроля доступа: мы принимаем разумные меры, чтобы не допустить несанкционированного использование личных данных. Эти меры зависят от характера обработки и могут включать, помимо прочего,
"несанкционированного использование"

2022-09-12 09:57 UTC, vbagirov commented on vpn_privacy_policy/ru/privacy-main.md
> +* Резервное копирование данных: мы регулярно делаем резервные копии баз данных, они зашифрованы, чтобы гарантировать защиту личных данных от случайного уничтожения или потери, когда они находятся у н
звучит как будто шифрование спасает "от случайного уничтожения или потери". Скорее резервное копирование помогает от случайного уничтожения или потери, а шифрование помогает чтоб в случае потери ими нельзя было воспользоваться

2022-09-12 11:19 UTC, el-termikael commented on vpn_privacy_policy/ru/privacy-main.md
> +ADGUARD SOFTWARE LIMITED (далее «мы») собирает и обрабатывает ваши личные данные в соответствии с этой Политикой конфиденциальности и в согласии с применимыми законами о защите данных. В данной Полит
мне не нравится с большой( может, так принято в политиках конфиденциальности, но выглядит зашкварно, как по мне

2022-09-12 12:26 UTC, vbagirov commented on vpn_privacy_policy/ru/privacy-main.md
> +ADGUARD SOFTWARE LIMITED (далее «мы») собирает и обрабатывает ваши личные данные в соответствии с этой Политикой конфиденциальности и в согласии с применимыми законами о защите данных. В данной Полит
Погуглил немного, судя по всему можно писать с маленькой, это не критично.

2022-09-14 13:29 UTC, ameshkov requested changes

2022-09-14 13:29 UTC, ameshkov commented on vpn_privacy_policy/ru/privacy-main.md
> +# Политика конфиденциальности AdGuard VPN
Где-то должно быть указано, что это - не главная версия, а просто перевод английской + ссылка на нее

2022-09-14 15:42 UTC, ameshkov approved these changes

2022-09-14 15:52 UTC, vbagirov approved these changes

2022-09-14 15:52 UTC, merged