Added biennial subscriptions
AdguardTeam/LegalDocs pull request #76
Opened 2022-09-19 13:22 UTC by nataMai

2022-09-19 13:38 UTC, el-termikael requested changes

2022-09-19 13:38 UTC, el-termikael commented on vpn_eula/en/EULA.md
> +In order to use the unlimited version of AdGuard VPN, you need to purchase a subscription: Monthly, Annual, or Biennial. Once you purchase a subscription, it is automatically linked to your AdGuard p
ой, ты же писала, что для контракта лучше monthly, one-year, and two-year subscription

2022-09-19 13:49 UTC, nataMai commented on vpn_eula/en/EULA.md
> +In order to use the unlimited version of AdGuard VPN, you need to purchase a subscription: Monthly, Annual, or Biennial. Once you purchase a subscription, it is automatically linked to your AdGuard p
Option A (law:  Monthly, Annual, Biennial    
Option B: Monthly, One-Year, Two-Year

Поскольку тут было Monthly, Annual - то я добавила Biennial

2022-09-20 08:33 UTC, el-termikael approved these changes

2022-09-20 08:33 UTC, merged