translated the AdGuard VPN EULA to Russian
AdguardTeam/LegalDocs pull request #79
Opened 2022-09-30 11:10 UTC by el-termikael

2022-09-30 13:10 UTC, vbagirov requested changes

2022-09-30 13:10 UTC, vbagirov commented on vpn_eula/ru/EULA.md
> +1.3. Чтобы использовать AdGuard VPN, вы должны установить это ПО и зарегистрироваться, используя адрес электронной почты. Укажите действительный адрес почты для создания учётной записи пользователя A
может быть my.adguard.com указать лучше?

2022-09-30 13:10 UTC, vbagirov commented on vpn_eula/ru/EULA.md
> +2.3. Если вы не отменили автооплату, средства будут списаны с вашего счёта автоматически, и лицензия AdGuard будет продлена. Если вы отключите автоматическое продление, то до истечения срока действия
точно лицензия?

2022-09-30 13:10 UTC, vbagirov commented on vpn_eula/ru/EULA.md
> +4.1. Вы не можете делать или распространять копии ПО или передавать его в электронном виде с одного компьютера на другой или по сети.
откуда эта фраза? мы сами апк раздаём иногда, например

2022-09-30 13:10 UTC, vbagirov commented on vpn_eula/ru/EULA.md
> +4.9. В случае нарушения мы оставляем за собой право заблокировать аккаунт или ограничить доступ к AdGuard VPN по нашему собственному усмотрению. AdGuard VPN может заблокировать аккаунт или ограничить
AdGuard VPN может заблокировать аккаунт или ограничить доступ  мгновенно и без какого-либо уведомления - он сам это делает? Или всё же это делает компания?

Плюс в этой фразе лишний пробел

2022-09-30 13:10 UTC, vbagirov commented on vpn_eula/ru/EULA.md
> +5.1. Adguard Software Limited гарантирует строгую политику без логирования для сервиса AdGuard VPN: во время его использования ваши действия не отслеживаются, не записываются, не фиксируются, не хран
точно надо здесь это писать? может просто достаточно сослаться на приваси полиси?

2022-09-30 13:10 UTC, vbagirov commented on vpn_eula/ru/EULA.md
> +
надо ли где-то в самом начале указать, что юр.силу несёт англ соглашение, а это перевод?

2022-09-30 13:44 UTC, el-termikael commented on vpn_eula/ru/EULA.md
> +5.1. Adguard Software Limited гарантирует строгую политику без логирования для сервиса AdGuard VPN: во время его использования ваши действия не отслеживаются, не записываются, не фиксируются, не хран
я не знаю, я не юрист(

2022-10-03 08:29 UTC, vbagirov approved these changes

2022-10-03 08:29 UTC, merged